### ISSUE TITLE
Slow connection clean up after `ed25519` handshake failure

### ISSUE THREAD

**Issue by tegefaulkes** [MatrixAI/js-quic#11] opened 2023-04-21 05:35 UTC
### Specification

There is an odd delay when cleaning up the `QUICConnection` after a tls handshake error. After the client checks the server's certs and fails it, it sends the `CC` frame to close the connection. for a `RSA` cert the server enters draining and then the close state very quickly. But for a `ed25519` cert the server processes the `CC` frame, waits an odd 3-ish seconds using the `timeout()`, `onTimeout()` timing mechanism and then enters the close state.

I don't see a reason why this would behave differently for an `ed25519` cert compared to an `RSA` one. I've been over the internal logic and I think I'm handling all the events when and as intended. This 3 second delay is clearly being set after processing the `CC` frame with `recv()` on the server side AND doing processing a `send()`. This is also after both sides have entered the draining state, so no new packets are going to be sent between them. 

Unless this is intended behaviour for handshakes with `ed25519` certs, I can only assume this is some kind of bug. I've posed an upstream issue for this at  https://github.com/cloudflare/quiche/issues/1488.

### Additional context

* Related https://github.com/cloudflare/quiche/issues/1488
* Related #9

### Tasks

1. Determine the cause of this delay.
2. Fix the problem.

**Comment by CMCDragonkai** [comment] 2023-05-26 00:55
It's also for ECDSA keypair.

**Comment by CMCDragonkai** [comment] 2023-07-06 06:45
This is understood why now. It does happen under specific circumstances. Not a bug on our side. Fixed by !26.

**Closed by CMCDragonkai** 2023-07-06 06:45 UTC
Labels: development
